# SonarQube server connection details
sonar.host.url=http://168.231.120.176:9000/
sonar.login=squ_f44d9d94bb4d4d835ec75f0ad54af622a746ec21

# Project identificationu
sonar.projectKey=Pairlix-user-android
sonar.projectName=Pairlix-user-android
sonar.projectVersion=1.0

# Source code directories
sonar.sources=.


# Language specific settings
sonar.language=js
sonar.sources.inclusions=**/*.js


# Encoding of source files
sonar.sourceEncoding=UTF-8

# Analysis exclusions (adjust as needed)
#sonar.exclusions=node_modules/**/*, coverage/**/*

# Coverage reports (for example, if using Istanbul for coverage)
#sonar.javascript.lcov.reportPaths=coverage/lcov-report/lcov.info
