package com.pairlix.dating.response

data class UpdateLanguageResponse(
    var `data`: Data? = null,
    var message: String? = null,
    var success: Boolean? = null
)
{
data class Data(
    var _id: String? = null,
    var accessToken: String? = null,
    var activePlan: String? = null,
    var activePlanType: Int? = null,
    var activityScore: Double? = null,
    var age: Int? = null,
    var ageSetting: Boolean? = null,
    var ageSettings: Boolean? = null,
    var behaviorScore: Double? = null,
    var behavioralScore100: Int? = null,
    var blurMyProfile: Boolean? = null,
    var blurProfile: Boolean? = null,
    var boostEndTime: String? = null,
    var boostStartTime: String? = null,
    var city: String? = null,
    var cityAr: Any? = null,
    var continousMatches: Any? = null,
    var countryCode: String? = null,
    var countryIso: String? = null,
    var countryName: String? = null,
    var countryNameAr: Any? = null,
    var createdAt: Long? = null,
    var dailyActivityScore: Int? = null,
    var dailySwipeCount: Int? = null,
    var day1ReminderSent: Boolean? = null,
    var day3ReminderSent: Boolean? = null,
    var deviceToken: String? = null,
    var deviceType: String? = null,
    var dislikes: Any? = null,
    var distanceSetting: Boolean? = null,
    var distanceSettings: Boolean? = null,
    var dob: String? = null,
    var email: String? = null,
    var ethnicity: Any? = null,
    var firstName: String? = null,
    var gender: String? = null,
    var hasABio: Boolean? = null,
    var isActive: Boolean? = null,
    var isBlocked: Boolean? = null,
    var isBoostActive: Boolean? = null,
    var isDeleted: Boolean? = null,
    var isMailOtpVerified: Boolean? = null,
    var isMatched: Boolean? = null,
    var isOnline: Boolean? = null,
    var isPhoneOtpVerified: Boolean? = null,
    var isProfileCompleted: Boolean? = null,
    var isUserOnHomePage: Boolean? = null,
    var isUserVerified: Int? = null,
    var language: String? = null,
    var lastActive: Boolean? = null,
    var lastActiveAt: String? = null,
    var lastBehaviorCalculatedAt: String? = null,
    var lastLogin: String? = null,
    var lastName: String? = null,
    var lastOnline: Any? = null,
    var likes: Any? = null,
    var likesToday: Int? = null,
    var location: Location? = null,
    var locationPermission: LocationPermission? = null,
    var locationSetting: Boolean? = null,
    var locationSettings: Boolean? = null,
    var messageFilter: Int? = null,
    var notificationPermission: Boolean? = null,
    var notificationSetting: Int? = null,
    var notifyOnline: Boolean? = null,
    var passesToday: Int? = null,
    var personalDetails: String? = null,
    var phoneNumber: String? = null,
    var planExpiry: String? = null,
    var privateAccount: Boolean? = null,
    var profileImages: List<String?>? = null,
    var profileStatus: Int? = null,
    var rejectionReason: String? = null,
    var seeFilter: Int? = null,
    var socialType: Any? = null,
    var socketId: List<String?>? = null,
    var superlikes: Any? = null,
    var totalActivityScore: Int? = null,
    var uniqueId: String? = null,
    var updatedAt: Long? = null
)

data class Location(
    var coordinates: List<Any?>? = null,
    var type: String? = null
)

data class LocationPermission(
    var allow: Boolean? = null,
    var deny: Boolean? = null
)}